[package]
name = "jsonmodem-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.4.1", features = ["derive"] }
libfuzzer-sys = { version = "0.15.3", package = "libafl_libfuzzer" }
rand = "0.9.1"
serde_json = "1.0.140"

[dependencies.jsonmodem]
path = "../crates/jsonmodem"

[[bin]]
name = "fuzz_jsonmodem"
path = "fuzz_targets/fuzz_jsonmodem.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_jsonmodem_buffers"
path = "fuzz_targets/fuzz_jsonmodem_buffers.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_jsonmodem_values"
path = "fuzz_targets/fuzz_jsonmodem_values.rs"
test = false
doc = false
bench = false
