//! Types and events emitted by the streaming JSON parser.
//!
//! `ParseEvent` enumerates parser outputs, indicating the JSON value type and
//! its path within the document. `PathItem` represents a key or index in a
//! JSON path.

use core::fmt::Debug;

use crate::{StdBackend, backend::StdPath, context::ValueCtx};

// Helper used solely by serde `skip_serializing_if` to omit `is_final` when it
// is `false`.
#[doc(hidden)]
#[cfg(any(test, feature = "serde"))]
#[expect(clippy::trivially_copy_pass_by_ref)]
fn is_false(b: &bool) -> bool {
    !*b
}
/// An event generated by the streaming JSON parser.
///
/// Represents a JSON parsing event, indicating the type of value, any relevant
/// data, and the path to that value within the document.
///
/// The `path` is a sequence of `PathItem` starting at the root. For example,
/// the first element in an array has path `[PathItem::Index(0)]`.
#[cfg_attr(
    any(test, feature = "serde"),
    derive(serde::Serialize, serde::Deserialize)
)]
#[cfg_attr(
    any(test, feature = "serde"),
    serde(
        tag = "kind",
        bound = "
        P : serde::Serialize + serde::de::DeserializeOwned,
        <B as ValueCtx>::Null       : serde::Serialize + serde::de::DeserializeOwned,
        <B as ValueCtx>::Bool       : serde::Serialize + serde::de::DeserializeOwned,
        <B as ValueCtx>::Num<'src>  : serde::Serialize + serde::de::DeserializeOwned,
        <B as ValueCtx>::Str<'src>  : serde::Serialize + serde::de::DeserializeOwned,
        <B as ValueCtx>::Value      : serde::Serialize + serde::de::DeserializeOwned
        "
    )
)]
#[derive(PartialEq)]
pub enum ParseEvent<'src, P: Debug = StdPath, B: ValueCtx = StdBackend> {
    /// A JSON `null` value.
    Null {
        /// The path to the value.
        path: P,
    },
    /// A JSON `true` or `false` value.
    Boolean {
        /// The path to the value.
        path: P,
        /// The boolean value.
        value: B::Bool,
    },
    /// A JSON number value.
    ///
    /// TODO: Support an `arbitrary_precision` feature that allows this value to
    /// be an arbitrarily large.
    Number {
        /// The path to the value.
        path: P,
        /// The number value.
        value: B::Num<'src>,
    },
    /// A JSON string value.
    String {
        /// The path to the string value.
        path: P,
        /// Fragment of the string value.
        fragment: B::Str<'src>,
        /// Whether this is the first fragment of a string value.
        #[cfg_attr(
            any(test, feature = "serde"),
            serde(skip_serializing_if = "crate::event::is_false")
        )]
        is_initial: bool,
        /// Whether this is the last fragment of a string value.
        #[cfg_attr(
            any(test, feature = "serde"),
            serde(skip_serializing_if = "crate::event::is_false")
        )]
        is_final: bool,
    },
    /// Marks the start of a JSON array.
    ArrayBegin {
        /// The path to the value.
        path: P,
    },
    /// Marks the end of a JSON array, optionally including its value.
    ArrayEnd {
        /// The path to the value.
        path: P,
    },
    /// Marks the start of a JSON object.
    ObjectBegin {
        /// The path to the value.
        path: P,
    },
    /// Marks the end of a JSON object, optionally including its value.
    ObjectEnd {
        /// The path to the value.
        path: P,
    },
}

impl<P: Debug, B: ValueCtx> Debug for ParseEvent<'_, P, B> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Null { path } => f.debug_struct("Null").field("path", path).finish(),
            Self::Boolean { path, value } => f
                .debug_struct("Boolean")
                .field("path", path)
                .field("value", value)
                .finish(),
            Self::Number { path, value } => f
                .debug_struct("Number")
                .field("path", path)
                .field("value", value)
                .finish(),
            Self::String {
                path,
                fragment,
                is_initial,
                is_final,
            } => f
                .debug_struct("String")
                .field("path", path)
                .field("fragment", fragment)
                .field("is_initial", is_initial)
                .field("is_final", is_final)
                .finish(),
            Self::ArrayBegin { path } => f.debug_struct("ArrayBegin").field("path", path).finish(),
            Self::ArrayEnd { path } => f.debug_struct("ArrayEnd").field("path", path).finish(),
            Self::ObjectBegin { path } => {
                f.debug_struct("ObjectBegin").field("path", path).finish()
            }
            Self::ObjectEnd { path } => f.debug_struct("ObjectEnd").field("path", path).finish(),
        }
    }
}

impl<'src, P: Debug, B: ValueCtx> From<ParseEvent<'src, &'_ P, B>> for ParseEvent<'src, P, B>
where
    P: Clone,
{
    fn from(value: ParseEvent<'src, &'_ P, B>) -> Self {
        match value {
            ParseEvent::Null { path } => ParseEvent::Null { path: path.clone() },
            ParseEvent::Boolean { path, value } => ParseEvent::Boolean {
                path: path.clone(),
                value,
            },
            ParseEvent::Number { path, value } => ParseEvent::Number {
                path: path.clone(),
                value,
            },
            ParseEvent::String {
                path,
                fragment,
                is_initial,
                is_final,
            } => ParseEvent::String {
                path: path.clone(),
                fragment,
                is_initial,
                is_final,
            },
            ParseEvent::ArrayBegin { path } => ParseEvent::ArrayBegin { path: path.clone() },
            ParseEvent::ArrayEnd { path } => ParseEvent::ArrayEnd { path: path.clone() },
            ParseEvent::ObjectBegin { path } => ParseEvent::ObjectBegin { path: path.clone() },
            ParseEvent::ObjectEnd { path } => ParseEvent::ObjectEnd { path: path.clone() },
        }
    }
}

impl<'src, P: Debug, Ctx: ValueCtx> ParseEvent<'src, P, Ctx> {
    /// Returns the path to the value.
    pub fn path(&self) -> &P {
        match self {
            ParseEvent::Null { path }
            | ParseEvent::Boolean { path, .. }
            | ParseEvent::Number { path, .. }
            | ParseEvent::String { path, .. }
            | ParseEvent::ArrayBegin { path }
            | ParseEvent::ArrayEnd { path, .. }
            | ParseEvent::ObjectBegin { path }
            | ParseEvent::ObjectEnd { path, .. } => path,
        }
    }

    /// Sets the path to a new value.
    pub fn with_path<U: Debug>(self, path: U) -> ParseEvent<'src, U, Ctx> {
        match self {
            ParseEvent::Null { .. } => ParseEvent::Null { path },
            ParseEvent::Boolean { value, .. } => ParseEvent::Boolean { path, value },
            ParseEvent::Number { value, .. } => ParseEvent::Number { path, value },
            ParseEvent::String {
                fragment,
                is_initial,
                is_final,
                ..
            } => ParseEvent::String {
                path,
                fragment,
                is_initial,
                is_final,
            },
            ParseEvent::ArrayBegin { .. } => ParseEvent::ArrayBegin { path },
            ParseEvent::ArrayEnd { .. } => ParseEvent::ArrayEnd { path },
            ParseEvent::ObjectBegin { .. } => ParseEvent::ObjectBegin { path },
            ParseEvent::ObjectEnd { .. } => ParseEvent::ObjectEnd { path },
        }
    }
}

#[cfg(test)]
#[doc(hidden)]
pub mod test_util {
    #![allow(dead_code)]
    use alloc::vec::Vec;
    /// Reconstructs the fully materialised JSON root values from a stream of
    /// `ParseEvent`s.
    ///
    /// The returned vector contains **one entry per root** in the order they
    /// appeared in the input. For example `1 2 [3]` yields
    /// `[Value::Number(1.0), Value::Number(2.0), Value::Array([3])]`.
    ///
    /// ---
    ///
    /// The streaming parser purposefully avoids building up complete `Value`
    /// trees while it tokenises the input.  For use-cases that need the
    /// fully materialised document (e.g. property-based round- trip tests)
    /// the crate exposes a small, allocation-friendly helper that rebuilds
    /// one or more `Value`s from the flat `ParseEvent` stream.
    ///
    /// The algorithm is deliberately simple:
    /// 1. Maintain a single mutable `Value` representing the *current* root
    ///    that is under construction.  A `Vec<Value>` is used to collect
    ///    finished roots so that multi-value streams like `1 2 3` are
    ///    supported.
    /// 2. For every `StartArray` / `StartObject` and `PrimitiveValue` event we
    ///    *insert* the matching placeholder / leaf at the provided `path`.  A
    ///    lightweight `insert_at_path` routine grows intermediate structures
    ///    on-demand and resizes arrays when necessary.
    /// 3. A root is considered *finished* when we receive either
    ///
    ///     - `PrimitiveValue` with an empty `path` (primitive roots), or
    ///     - `EndArray` / `EndObject` with an empty `path` (composite roots).
    ///
    ///    At that point a clone of the currently built value is pushed onto the
    ///    result vector and the buffer is reset.
    ///
    /// This avoids any expensive deep copies – only the final `clone()` at root
    /// completion is required and unavoidable because the caller may retain the
    /// returned list while more events are fed in.
    use alloc::{collections::BTreeMap, sync::Arc};

    use super::*;
    use crate::*;

    type Map = BTreeMap<Arc<str>, Value>;

    pub fn reconstruct_values<'a, I>(events: I) -> Vec<Value>
    where
        I: IntoIterator<Item = ParseEvent<'a, Vec<PathItem>, StdBackend>>,
    {
        let mut finished_roots = Vec::new();
        let mut current_root = Value::Null;
        let mut building_root = false;

        for evt in events {
            match &evt {
                // ----------------------------------------------------------------------------------
                // Container open – insert an empty placeholder so that later children have a slot
                // to land in.
                ParseEvent::ArrayBegin { path } => {
                    insert_at_path(&mut current_root, path, Value::Array(Vec::new()));
                    if path.is_empty() {
                        building_root = true;
                    }
                }
                ParseEvent::ObjectBegin { path } => {
                    insert_at_path(&mut current_root, path, Value::Object(Map::new()));
                    if path.is_empty() {
                        building_root = true;
                    }
                }

                // ----------------------------------------------------------------------------------
                // Leaf value – insert at its destination path.  If the path is empty we finish the
                // root.
                ParseEvent::Null { path } => {
                    insert_at_path(&mut current_root, path, Value::Null);
                    if path.is_empty() {
                        finished_roots.push(Value::Null);
                        current_root = Value::Null;
                        building_root = false;
                    }
                }
                ParseEvent::Boolean { path, value } => {
                    insert_at_path(&mut current_root, path, Value::Boolean(*value));
                    if path.is_empty() {
                        finished_roots.push(Value::Boolean(*value));
                        current_root = Value::Null;
                        building_root = false;
                    }
                }
                ParseEvent::Number { path, value } => {
                    insert_at_path(&mut current_root, path, Value::Number(*value));
                    if path.is_empty() {
                        finished_roots.push(Value::Number(*value));
                        current_root = Value::Null;
                        building_root = false;
                    }
                }
                // ----------------------------------------------------------------------------------
                // Streaming string fragments – accumulate string content and start a root on first
                // fragment.
                ParseEvent::String {
                    path,
                    fragment,
                    is_final,
                    ..
                } => {
                    append_string_at_path(&mut current_root, path, fragment.as_ref());

                    if *is_final && path.is_empty() {
                        finished_roots.push(current_root.clone());
                        current_root = Value::Null;
                        building_root = false;
                    } else if path.is_empty() {
                        building_root = true;
                    }
                }

                // ----------------------------------------------------------------------------------
                // Container close – push the fully built root when the closed container sits at the
                // top level.
                ParseEvent::ArrayEnd { path, .. } | ParseEvent::ObjectEnd { path, .. } => {
                    if path.is_empty() && building_root {
                        finished_roots.push(current_root.clone());
                        current_root = Value::Null;
                        building_root = false;
                    }
                }
            }
        }

        // If a top-level string (or other root) was started but never terminated via
        // Complete, treat it as finished at end-of-stream.
        if building_root {
            finished_roots.push(current_root);
        }
        finished_roots
    }

    /// Inserts `val` into `target` at the location described by `path`,
    /// creating intermediate containers as necessary.  When the final path
    /// component denotes an array index the underlying vector is
    /// automatically resized (filled with `Value::Null`).
    fn insert_at_path(target: &mut Value, path: &Path, val: Value) {
        use crate::PathItem;

        if path.is_empty() {
            *target = val;
            return;
        }

        let mut current = target;
        // Traverse all but the last component, creating intermediate containers
        // on-demand.
        for comp in &path[..path.len() - 1] {
            match comp {
                PathItem::Key(k) => {
                    if let Value::Object(map) = current {
                        current = map.entry(k.clone()).or_insert(Value::Null);
                    } else {
                        *current = Value::Object(Map::new());
                        if let Value::Object(map) = current {
                            current = map.entry(k.clone()).or_insert(Value::Null);
                        }
                    }
                }
                PathItem::Index(i) => {
                    let i = *i;
                    if let Value::Array(vec) = current {
                        if i >= vec.len() {
                            vec.resize(i + 1, Value::Null);
                        }
                        current = &mut vec[i];
                    } else {
                        *current = Value::Array(Vec::new());
                        if let Value::Array(vec) = current {
                            if i >= vec.len() {
                                vec.resize(i + 1, Value::Null);
                            }
                            current = &mut vec[i];
                        }
                    }
                }
            }
        }

        // Set the final component.
        match path.last().unwrap() {
            PathItem::Key(k) => {
                if let Value::Object(map) = current {
                    map.insert(k.clone(), val);
                } else {
                    // Replace the current slot with a new object containing the desired key/value.
                    let mut map = Map::new();
                    map.insert(k.clone(), val);
                    *current = Value::Object(map);
                }
            }
            PathItem::Index(i) => {
                let i = *i;
                if let Value::Array(vec) = current {
                    if i >= vec.len() {
                        vec.resize(i + 1, Value::Null);
                    }
                    vec[i] = val;
                } else {
                    let mut vec = Vec::new();
                    if i >= vec.len() {
                        vec.resize(i + 1, Value::Null);
                    }
                    vec[i] = val;
                    *current = Value::Array(vec);
                }
            }
        }
    }

    /// Insert or append a string fragment into `target` at the given `path`.
    fn append_string_at_path(target: &mut Value, path: &Path, fragment: &str) {
        use crate::PathItem;

        if path.is_empty() {
            if let Value::String(s) = target {
                s.push_str(fragment);
            } else {
                *target = Value::String(fragment.into());
            }
            return;
        }
        let mut cur = target;
        // Traverse to the container for the final component
        let len = path.len();
        for comp in &path[..len - 1] {
            match comp {
                PathItem::Key(k) => {
                    if let Value::Object(map) = cur {
                        cur = map.entry(k.clone()).or_insert(Value::Null);
                    } else {
                        *cur = Value::Object(Map::new());
                        if let Value::Object(map) = cur {
                            cur = map.entry(k.clone()).or_insert(Value::Null);
                        }
                    }
                }
                PathItem::Index(i) => {
                    let i = *i;
                    if let Value::Array(vec) = cur {
                        if i >= vec.len() {
                            vec.resize(i + 1, Value::Null);
                        }
                        cur = &mut vec[i];
                    } else {
                        *cur = Value::Array(Vec::new());
                        if let Value::Array(vec) = cur {
                            if i >= vec.len() {
                                vec.resize(i + 1, Value::Null);
                            }
                            cur = &mut vec[i];
                        }
                    }
                }
            }
        }
        // Append or insert at the final component
        match path.last().unwrap() {
            PathItem::Key(k) => {
                if let Value::Object(map) = cur {
                    if let Some(Value::String(s)) = map.get_mut(k) {
                        s.push_str(fragment);
                    } else {
                        map.insert(k.clone(), Value::String(fragment.into()));
                    }
                } else {
                    let mut map = Map::new();
                    map.insert(k.clone(), Value::String(fragment.into()));
                    *cur = Value::Object(map);
                }
            }
            PathItem::Index(i) => {
                let i = *i;
                if let Value::Array(vec) = cur {
                    if i < vec.len() {
                        if let Value::String(s) = &mut vec[i] {
                            s.push_str(fragment);
                        } else {
                            vec[i] = Value::String(fragment.into());
                        }
                    } else {
                        vec.resize(i + 1, Value::Null);
                        vec[i] = Value::String(fragment.into());
                    }
                } else {
                    let mut vec = Vec::new();
                    if i >= vec.len() {
                        vec.resize(i + 1, Value::Null);
                    }
                    vec[i] = Value::String(fragment.into());
                    *cur = Value::Array(vec);
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::{PathCtx, StdBackend};

    #[test]
    fn size_of_parse_event() {
        use core::mem::size_of;
        assert_eq!(
            size_of::<ParseEvent<<StdBackend as PathCtx>::Path, StdBackend>>(),
            56
        );
    }
}
